### ISSUE TITLE
Installation savely possible for these specs?

### ISSUE THREAD

**Issue by LarsHill** [matpool/mpu#10]
Hi, 

Thanks for this kernel extension.

Is it save to install with the following specs?
- NVIDIA-SMI: 470.86
- Driver Version: 470.86
- CUDA Version: 11.4
- Kernel: 3.10.0-1160.45.1.el7.x86_64

Since I am not familiar with kernel extensions, I am a little hesitant to simply give it a try.
If no weird side effects can occur I would give it a shot and if it works you can update the `README` accordingly, adding the above specs as being compatible.

Thanks for your input.

Best regards
Lars

Edit*: Also, if you find the time, can you maybe explain how your solution is different from this repo [https://github.com/gh2o/nvidia-pidns](https://github.com/gh2o/nvidia-pidns)? It was also referenced in the corresponding nvidia-docker Github issue [https://github.com/NVIDIA/nvidia-docker/issues/179](https://github.com/NVIDIA/nvidia-docker/issues/179).

**Comment by 0of** [comment]
You can try it in a GPU passthrough virtual machine
This module only intercepts specific kernel events. In the worst case, if kernel indeed panics, the system will go back to normal after kernel reboots. In rare cases, it'll let your kernel irrecoverable

It may work with your provided specs. However, NVIDIA driver changes its nvidia-smi impl in different versions. 

Besides, I didn't walk through the project nvidia-pidns, but IMO the impls are similar in casting pid from different pid namespaces
