### ISSUE TITLE
It doesn't work after restarting the host.

### ISSUE THREAD

**Issue by siaimes** [matpool/mpu#8]
It doesn't work after restarting the host. The current solution is to re-execute the `make install` command.

**Comment by 0of** [comment]
According to your distributions you can modify `/etc/modules` or `/etc/modprobe.d/` for loading module (mpu.ko) during boot time.

**Comment by siaimes** [comment]
@0of Thanks for your reply, I tested it based on the information you provided and it worked. I modified the Makefile and submitted a PR, you can consider whether to merge it or not.

**Comment by 0of** [comment]
thanks for your contribution.
i'll close the issue.
